apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.228.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2EI9hrbEC53Blu/aQmoSkWcbQcM96IJjm1Y7+JG9q+bfpDwWtW70Wi15OBpgxORMvfUd3ulEpOWilsW/zapXvJStP8C24wMG6GgISI+Sa9jU6L6lYcDlF9ls4UfgiDWtJBXniPhXzzRjQTBzcwIpQG3mAqc/J/ad0ypoLVxI2LO5/V83Iz0l/OmyIZSW1zMXLy3+6P+xbDaotExt26Td+fmYZb8N5wOGAjNmTlMN2lG1tlaKfiTS+6480pgTeeTFy5PJWVL+h8/EA7vR1IQnl4fcG6TYA7ZXNlldbuAYVw22bi2OoyFPPsqmtkBBreRoO81oycXcm+irCTwANQooHd6uZRfkomrgGAAhvupUkEZ/3JAVXmAkBuPEykrrtk37ngc3YiEDluY2hvJRwUwtz7WPBzJ/MWVVzvuhYDMXHZGycNM5CA50h5Sc6brWkJZzffylyUIScLQSAIeQEApCdDqYOBUvnjGZ/sDNhGq/t8RyPoNojgVWpZKO88zt6+eU= kor@vu173'
