---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: upgrade all packages
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"


  roles:
    - geerlingguy.firewall
    - geerlingguy.haproxy
    - geerlingguy.apache
