---
- hosts: okd4_services
  become: yes
  gather_facts: yes


  vars_files:
    - vars.yml

  pre_tasks:
    - name: wait for host to finish reb00t
      wait_for:
        port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10  # Do not check for at least 10 sec
      connection: local
      become: no

    - name: upgrade all packages
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Ensure required packeages is installed.
      dnf:
        name:
          - python3-libsemanage
        state: latest

    - name: Set haproxy_connect_any flag on and keep it persistent across reboots
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Set httpd_read_user_content flag on and keep it persistent across reboots
      seboolean:
        name: httpd_read_user_content
        state: yes
        persistent: yes

  roles:
    - geerlingguy.haproxy
    - geerlingguy.apache
    - resolv.conf


  tasks:
    - name: Configure open ports with firewalld.
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        - { state: 'enabled', port: '22/tcp' }
        # HA_Proxy port 80 and 443
        - { state: 'enabled', port: '80/tcp' }
        - { state: 'enabled', port: '443/tcp' }
        # Bind DNS port
        - { state: 'enabled', port: '53/udp' }
        # Apache port 8080
        - { state: 'enabled', port: '8080/tcp' }
        # OKD firewall ports
        - { state: 'enabled', port: '6443/tcp' }
        - { state: 'enabled', port: '22623/tcp' }

    - name: Configure and run Bind service
      import_tasks: tasks/apacheConfig.yml

    - name: Configure and run Bind service
      import_tasks: tasks/bindDnsConfig.yml

    - name: Configure and run HAPROXY
      import_tasks: tasks/haproxyConfig.yml



