---
- hosts: okd4_services
  become: yes
  gather_facts: yes


  vars_files:
    - vars.yml

  pre_tasks:
    - name: wait for host to finish reb00t
      wait_for:
        port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10  # Do not check for at least 10 sec
      connection: local
      become: no

    - name: upgrade all packages
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Ensure required packeages is installed.
      dnf:
        name:
          - python3-libsemanage
          - curl
          - tar
          - rsync
          - keepalived
        state: latest

    - name: Set haproxy_connect_any flag on and keep it persistent across reboots
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Set httpd_read_user_content flag on and keep it persistent across reboots
      seboolean:
        name: httpd_read_user_content
        state: yes
        persistent: yes

    - name: Allow in selinux nfs shares
      seboolean:
        name: nfs_export_all_rw
        state: yes
        persistent: yes


  roles:
    - geerlingguy.haproxy
    - geerlingguy.apache
    - geerlingguy.nfs
    - resolv.conf


  tasks:
    - name: Open ports on firewalld
      import_tasks: tasks/openPorts.yml

    - name: Configure and run APACHE
      import_tasks: tasks/apacheConfig.yml

    - name: Configure and run HAPROXY
      import_tasks: tasks/haproxyConfig.yml

    - name: Configure NFS
      import_tasks: tasks/nfsShare.yml


- hosts: helper1
  become: yes
  gather_facts: yes

  tasks:
    - name: Configure and run Bind service
      import_tasks: tasks/bindDnsMasterConfig.yml

    - name: Configure and run keepAlived
      vars:
        keepalived_priority: 200
        keepalived_state: MASTER
        keepalived_vip: 192.168.122.212
        keepalived_vrid: 10
        keepalived_vrrp_instance_name: "HA_10"
        keepalived_auth_type: "PASS"
        keepalived_auth_pass: "1011"
      import_tasks: tasks/keepAlivedMasterConfig.yml

    #    - name: Configure OKD
    #      import_tasks: tasks/okdConfig.yml

- hosts: helper2
  become: yes
  gather_facts: yes

  tasks:
    - name: Configure and run Bind service
      import_tasks: tasks/bindDnsSlaveConfig.yml

    - name: Configure and run keepAlived
      vars:
        keepalived_priority: 100
        keepalived_state: BACKUP
        keepalived_vip: 192.168.122.212
        keepalived_vrid: 10
        keepalived_vrrp_instance_name: "HA_10"
        keepalived_auth_type: "PASS"
        keepalived_auth_pass: "1011"
      import_tasks: tasks/keepAlivedBackupConfig.yml


