---
- hosts: okd4_services
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=10
        become: false

    - name: upgrade all packages
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"


  roles:
    - geerlingguy.firewall
    - geerlingguy.haproxy
