---
- hosts: helper1
  gather_facts: yes
  vars:
    keepalived_priority: 200
    keepalived_state: MASTER
    keepalived_vip: 192.168.122.212
    keepalived_vrid: 10
    keepalived_vrrp_instance_name: "HA_10"
    keepalived_auth_type: "PASS"
    keepalived_auth_pass: "1011"
  tasks:
    - name: Add Keepalived config file
      template:
        dest: /etc/keepalived/keepalived.conf
        src: etc/keepalived/keepalived.conf.j2
      notify: Restart Keepalived

  handlers:
    - name: Restart Keepalived
      service:
        name: keepalived
        state: restarted

- hosts: helper2
  gather_facts: yes
  vars:
    keepalived_priority: 100
    keepalived_state: BACKUP
    keepalived_vip: 192.168.122.12
    keepalived_vrid: 10
    keepalived_vrrp_instance_name: "HA_10"
    keepalived_auth_type: "PASS"
    keepalived_auth_pass: "1011"
  tasks:
    - name: Add Keepalived config file
      template:
        dest: /etc/keepalived/keepalived.conf
        src: etc/keepalived/keepalived.conf.j2
      notify: Restart Keepalived

  handlers:
    - name: Restart Keepalived
      service:
        name: keepalived
        state: restarted