---
- name: Add Keepalived config file
  template:
    dest: /etc/keepalived/keepalived.conf
    src: template/keepalived.conf.j2

- name: Restart keepalive
  systemd:
    name: keepalived
    state: restarted